services:
  css-server:
    build:
      context: .
      args:
        DOWNLOAD_BUNDLE_URL: ${DOWNLOAD_BUNDLE_URL}
        CSS_DIR: ${CSS_DIR}
        STEAMCMD_DIR: ${STEAMCMD_DIR}
    volumes:
      - data:/home/steam/${CSS_DIR}
    # ports:
    #   - target: 27015
    #     published: ${PORT}
    #     protocol: udp
    #     mode: host

    #   - target: 27015
    #     published: ${PORT}
    #     protocol: tcp
    #     mode: host
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
    restart: unless-stopped

volumes:
  data:
