services:
  css-server:
    build:
      context: .
      args:
        DOWNLOAD_BUNDLE_URL: ${DOWNLOAD_BUNDLE_URL}
        CSS_DIR: ${CSS_DIR}
        STEAMCMD_DIR: ${STEAMCMD_DIR}
    volumes:
      - server_data: ${CSS_DIR}
    restart: unless-stopped
    network_mode: host

volumes:
  server_data:
